const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Nike Fit shirt',
      slug: 'nike-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 5,
      description: 'high quality shirt',
    },
    {
      _id: '3',
      name: 'Adidas Slim pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 30,
      countInStock: 15,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality pant',
    },
    {
      _id: '4',
      name: 'Adidas Fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 0,
      brand: 'Adidas',
      rating: 0,
      numReviews: 0,
      description: 'high quality pant',
    },
  ],
};

export default data;
